apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: d5cqm4qhz-go 
  janus-idp.io/tekton: d5cqm4qhz-go
  backstage.io/kubernetes-id: d5cqm4qhz-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: d5cqm4qhz-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml